[workspace]
resolver = "2"
members = [
    "trading_bots",
    "tui",
    "shared",
    "report_cli",
    "benchmarks",
    "training_log_server",
]

[patch.crates-io]
torch-sys = { path = "vendor/torch-sys-0.25.0" }

[patch."https://github.com/LaurentMazare/tch-rs.git"]
torch-sys = { path = "vendor/torch-sys-0.25.0" }
